### PR TITLE
Accessibility/inputs

### LINKED ISSUE #49: Access: button empty & Image size
What It Means:
A button or input that is empty or has no value text.

Why It Matters
When navigating to a button, descriptive text must be presented to screen reader users to indicate the function of the button.

How to Fix It
Place text content within the <button> element or give the <input> element a value attribute.

The Algorithm... in English
A `<button>` element is present that contains no text content (or alternative text), or an `<input type="submit">`, `<input type="button">`, or `<input type="reset">` has an empty or missing value attribute.

### PR DESCRIPTION
**Pull request by CaliHam**
### What is the feature?
This PR will close #49 and #38
Added button types, input types, and button aria labels. Also added a set height to recipe of the day image.
Accessibility score up by 4 points on lighthouse.

### CODE REVIEW

**Comment by CaliHam** [comment]
Removed alt text due for recipe boxes to redundancy, see below:

Screenshot 2023-06-01 at 12 57 24 PM

**Comment by CaliHam** [comment]
Screenshot 2023-06-01 at 1 02 10 PM
 Wooohooo!! 🎉

**Comment by CaliHam** [comment]
Screenshot 2023-06-01 at 1 03 10 PM
Also 100% on wave!

**Review by paulina-isabel — APPROVED** [review]
Awesome!

**Review by alivaditis — APPROVED** [review]
nice work adding the aria-labels!

**Review by jalbe0076 — APPROVED** [review]
100% nice!

**Pull request merged**
