### PR TITLE
Feature/filter by tag dom

### PR DESCRIPTION
**Pull request by jalbe0076**
### What is the feature?
- This PR will close https://github.com/jalbe0076/jalbe0076/issues/12
- Add dropdown to all categories button when you hover over the button populating it by recipe tags
-  Filter by the tag and display those recipes

### How you implemented the solution?
- Created the dropdown menu using CSS visibility and transitions
- Filtered by the tag by utilizing available functions. 

### Does it impact any other area of the project?
- Yes, you can now search by tag

### Any changes in the UI (Screenshots)?
image

### How to test the feature (A test scenario or any new setup)?
- Hover over the All Categories button and select a tag

### CODE REVIEW

**Comment by CaliHam** [comment]
Love the dropdown!! First thing I noticed was when clicking a category/tag, the header will say "Showing search results for ""..." , we should change this to say "Category Name"

**Review by alivaditis — APPROVED** [review]
Nice work!

**Review by paulina-isabel — APPROVED** [review]

**Comment by jalbe0076** [comment]
> 

Good catch! I'll go fix that!

**Comment by jalbe0076** [comment]
Fixed the missing search parameter by adding a conditional to the searchRecipe Function

**Pull request merged**
